// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderPractice.Data;

namespace OrderPractice.Migrations
{
    [DbContext(typeof(OrderPracticeContext))]
    [Migration("20200708060852_FixedRelationshipBeteweenOrdersStatus")]
    partial class FixedRelationshipBeteweenOrdersStatus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrderPractice.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<int>("OrderProductId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderProductId");

                    b.HasIndex("StatusCode");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = "A20202026001",
                            Cost = 90,
                            OrderProductId = 1,
                            Price = 100,
                            StatusCode = 1
                        },
                        new
                        {
                            OrderId = "A20202026002",
                            Cost = 100,
                            OrderProductId = 2,
                            Price = 120,
                            StatusCode = 1
                        },
                        new
                        {
                            OrderId = "A20202026003",
                            Cost = 150,
                            OrderProductId = 3,
                            Price = 200,
                            StatusCode = 1
                        },
                        new
                        {
                            OrderId = "A20202026004",
                            Cost = 120,
                            OrderProductId = 4,
                            Price = 150,
                            StatusCode = 1
                        });
                });

            modelBuilder.Entity("OrderPractice.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductName = "Product1"
                        },
                        new
                        {
                            ProductId = 2,
                            ProductName = "Product2"
                        },
                        new
                        {
                            ProductId = 3,
                            ProductName = "Product3"
                        },
                        new
                        {
                            ProductId = 4,
                            ProductName = "Product4"
                        });
                });

            modelBuilder.Entity("OrderPractice.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "Payment completed"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "To be shipped"
                        });
                });

            modelBuilder.Entity("OrderPractice.Models.Order", b =>
                {
                    b.HasOne("OrderPractice.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("OrderProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderPractice.Models.Status", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
